name: Backend CI

on:
  push:
    branches:
      - main
      - production
  pull_request:
    branches:
      - main
      - production

jobs:
  build-and-test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: backend/node_modules
          key: ${{ runner.os }}-backend-${{ hashFiles('backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-backend-

      - name: Install dependencies
        run: |
          cd backend
          npm ci

      - name: Run SonarCloud Analysis
        uses: SonarSource/sonarqube-scan-action@v4.1.0
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.sources=backend
            -Dsonar.exclusions=**/node_modules/**,**/dist/**
            -Dsonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Wait for SonarCloud processing
        run: sleep 30

      - name: Check Quality Gate
        run: |
          STATUS=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" "https://sonarcloud.io/api/qualitygates/project_status?projectKey=${{ secrets.SONAR_PROJECT_KEY }}" | jq -r '.projectStatus.status')
          echo "Quality Gate Status: $STATUS"
          if [[ "$STATUS" != "OK" ]]; then
            echo "Quality gate failed. Blocking pipeline."
            exit 1
          fi

      - name: Start backend server
        run: |
          cd backend
          npm start &
        env:
          NODE_ENV: test

      - name: Wait for the backend server to be ready
        run: |
          npx wait-on http://localhost:3000/db/all

      - name: Run tests with coverage
        run: |
          cd backend
          npm run test:ci

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: backend-coverage
          path: backend/coverage/

  docker-build-backend:
    needs: build-and-test-backend
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name == 'main' && 'Development' || 'Production' }}
      url: ${{ github.ref_name == 'production' && 'https://my-production-app.com' || 'https://my-dev-app.com' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t backend-app ./backend

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            docker tag backend-app ${{ secrets.DOCKER_USERNAME }}/backend-app:dev
            docker push ${{ secrets.DOCKER_USERNAME }}/backend-app:dev
          elif [[ "${{ github.ref_name }}" == "production" ]]; then
            docker tag backend-app ${{ secrets.DOCKER_USERNAME }}/backend-app:prod
            docker push ${{ secrets.DOCKER_USERNAME }}/backend-app:prod
          fi
