name: Frontend CI

on:
  push:
    branches:
      - main
      - production
  pull_request:
    branches:
      - main
      - production

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-frontend-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-frontend-

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Build application
        run: |
          cd frontend
          npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: frontend/dist/

  docker-build-and-push-frontend:
    needs: build-frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t frontend-app ./frontend

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Tag and push for Development environment
      - name: Push Docker Image (Development)
        if: github.ref_name == 'main'
        run: |
          docker tag frontend-app ${{ secrets.DOCKER_USERNAME }}/frontend-app:dev
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend-app:dev
        environment:
          name: Development

      # Tag and push for Production environment with manual approval
      - name: Push Docker Image (Production)
        if: github.ref_name == 'production'
        run: |
          docker tag frontend-app ${{ secrets.DOCKER_USERNAME }}/frontend-app:prod
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend-app:prod
        environment:
          name: Production
