name: Frontend CI

on:
  push:
    branches:
      - main
      - production
  pull_request:
    branches:
      - main
      - production

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-frontend-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-frontend-

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Build application
        run: |
          cd frontend
          npm run build

      - name: Run SonarCloud Analysis
        uses: sonarsource/sonarcloud-github-action@v1.10
        with:
          projectKey: ${{ secrets.SONAR_PROJECT_KEY }}
          organization: ${{ secrets.SONAR_ORGANIZATION }}
          token: ${{ secrets.SONAR_TOKEN }}
          args: >
            -Dsonar.sources=frontend
            -Dsonar.exclusions=**/node_modules/**,**/dist/**
            -Dsonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

      - name: Quality Gate Check
        run: |
          curl -u "${{ secrets.SONAR_TOKEN }}:" "https://sonarcloud.io/api/project_analyses/search?project=${{ secrets.SONAR_PROJECT_KEY }}" |
          jq '.analyses[0].status == "SUCCESS"' || exit 1

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: frontend/dist/

  docker-build-and-push-frontend:
    needs: build-frontend
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name == 'main' && 'Development' || 'Production' }}
      url: ${{ github.ref_name == 'production' && 'https://my-production-site.com' || 'https://my-dev-site.com' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t frontend-app ./frontend

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            docker tag frontend-app ${{ secrets.DOCKER_USERNAME }}/frontend-app:dev
            docker push ${{ secrets.DOCKER_USERNAME }}/frontend-app:dev
          elif [[ "${{ github.ref_name }}" == "production" ]]; then
            docker tag frontend-app ${{ secrets.DOCKER_USERNAME }}/frontend-app:prod
            docker push ${{ secrets.DOCKER_USERNAME }}/frontend-app:prod
          fi
